import type { MetadataRoute } from 'next';

// PWA manifest. Strings stay generic so a brand-name change doesn't need
// a code deploy — the doctor edits clinic_settings instead, and that
// already drives the landing page hero. App-tray name comes from this
// manifest though, so "Clinic" is the user-visible short label.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Clinic Booking',
    short_name: 'Clinic',
    description: 'Book medical appointments online',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#0d9488',
    orientation: 'portrait',
    icons: [
      // /icon, /icon0, /icon1 are generated by app/icon.tsx, app/icon0.tsx,
      // app/icon1.tsx via Next 16's icon convention. Ordered small to large
      // so installers pick the right size for the surface.
      {
        src: '/icon',
        sizes: '32x32',
        type: 'image/png',
      },
      {
        src: '/icon0',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon1',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
    ],
  };
}
